# rpmrebuild autogenerated specfile
#to build from spec using rpmbuild :
#ln -s / /tmp/buildroot
#rpmbuild --buildroot /tmp/buildroot -bb specfile
#rm /tmp/builroot

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    localhost
#BUILDTIME:    Wed Jan  7 04:36:53 2026
#SOURCERPM:    zfs-kmod-2.4.0-1.fc43.src.rpm

#RPMVERSION:   6.0.1
#COOKIE:       localhost 1767760612
#INSTALLTIME:  Wed Jan  7 04:41:35 2026

#OS:           linux
#SIZE:           7252050
#ARCHIVESIZE:           7253580
#ARCH:         aarch64
BuildArch:     aarch64
Name:          kmod-zfs-6.17.11-300.fc43.aarch64
Version:       2.4.0
Release:       1.fc43
License:       CDDL 
Group:         System Environment/Kernel
Summary:       zfs kernel module(s) for 6.17.11-300.fc43.aarch64

# full rpm name was:
# kmod-zfs-6.17.11-300.fc43.aarch64-2.4.0-1.fc43.aarch64


URL:           https://github.com/openzfs/zfs


Provides:      kernel-modules-for-kernel = 6.17.11-300.fc43.aarch64
Provides:      kmod(spl.ko)  
Provides:      kmod(zfs.ko)  
Provides:      kmod-zfs-6.17.11-300.fc43.aarch64 = 2.4.0-1.fc43
Provides:      kmod-zfs-6.17.11-300.fc43.aarch64(aarch-64) = 2.4.0-1.fc43
Provides:      kmod-zfs-uname-r = 6.17.11-300.fc43.aarch64
Provides:      modalias(char-major-10-249) = 2.4.0_1
Provides:      modalias(devname:zfs) = 2.4.0_1
Provides:      modalias(icp) = 2.4.0_1
Provides:      modalias(zavl) = 2.4.0_1
Provides:      modalias(zcommon) = 2.4.0_1
Provides:      modalias(zlua) = 2.4.0_1
Provides:      modalias(znvpair) = 2.4.0_1
Provides:      modalias(zunicode) = 2.4.0_1
Provides:      modalias(zzstd) = 2.4.0_1
Provides:      zfs-kmod = 2.4.0-1.fc43
Requires(post): /bin/sh  
Requires(postun): /bin/sh  
Requires(post): kmod  
Requires(postun): kmod  
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#Requires:      rpmlib(FileDigests) <= 4.6.0-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1
#Requires:      rpmlib(PayloadIsZstd) <= 5.4.18-1
Requires:      zfs-kmod-common >= 2.4.0


%description
This package provides the zfs kernel modules built for the Linux
kernel 6.17.11-300.fc43.aarch64 for the aarch64 family of processors.
%files
%dir %attr(0755, root, root) "/lib/modules/6.17.11-300.fc43.aarch64/extra"
%dir %attr(0755, root, root) "/lib/modules/6.17.11-300.fc43.aarch64/extra/zfs"
%attr(0644, root, root) "/lib/modules/6.17.11-300.fc43.aarch64/extra/zfs/spl.ko"
%attr(0644, root, root) "/lib/modules/6.17.11-300.fc43.aarch64/extra/zfs/zfs.ko"
%dir %attr(0755, root, root) "/usr/lib/.build-id"
%dir %attr(0755, root, root) "/usr/lib/.build-id/b3"
"/usr/lib/.build-id/b3/46f3527cd5530e25b814a07878305cc5355aed"
%dir %attr(0755, root, root) "/usr/lib/.build-id/ef"
"/usr/lib/.build-id/ef/05ae3030540b56c4c9e3207df5a298fd5709ee"


%post -p /bin/sh
[ "$(uname -r)" = "6.17.11-300.fc43.aarch64"  ] && /sbin/depmod -a > /dev/null || :


%postun -p /bin/sh
[ "$(uname -r)" = "6.17.11-300.fc43.aarch64"  ] && /sbin/depmod -a > /dev/null || :

%changelog
