[Service]
# return 1 if local digest matches remote digest. 0 if they differ
# 0 will allow ExecStart to run the upgrade
# Do upgrade if remote digest is not equal to any of current digests.
# Handles staged or rollback.
ExecCondition=/usr/bin/bash -vxeu -o pipefail -c ' \
booted_arch=$(rpm-ostree status --json | jq \'.deployments[] | select(.booted == true)."base-commit-meta"."ostree.container.image-config" | fromjson .architecture\'); \
booted_image_uri=$(rpm-ostree status --json | jq -r \'.deployments[] | select(.booted == true)."container-image-reference"\' | grep -oP ":(\\/{2})?\\K[^:]*?:[^:]*?$"); \
local_digests=$(rpm-ostree status --json | jq \'[.deployments[] | ."base-commit-meta"."ostree.manifest-digest"]\'); \
remote_digest=$(skopeo inspect --raw "docker://$booted_image_uri" | jq ".manifests[] | select(.platform.architecture == $booted_arch) | .digest"); \
echo "$local_digests" | jq -e "all(. != $remote_digest)" '

# the regex gets the image ref from the 2nd to last : (colon) character
# https://regex101.com/r/2lHe5V/2
# examples:
#   "container-image-reference" : "ostree-unverified-registry:ghcr.io/user/repo/pkg:tag",
#   "container-image-reference" : "ostree-image-signed:docker://ghcr.io/user/repo/pkg:tag"
# possible img reference formats: https://coreos.github.io/rpm-ostree/container/#url-format-for-ostree-native-containers
#   ostree-unverified-image:registry:<oci image>
#   ostree-unverified-image:docker://<oci image>
#   ostree-unverified-registry:<oci image>
#   ostree-remote-image:<ostree remote>:registry:<oci image>
#   ostree-remote-image:<ostree remote>:docker://<oci image>
#   ostree-remote-registry:<ostree remote>:<oci image>
#   ostree-image-signed:registry:<oci image>
#   ostree-image-signed:docker://<oci image>
#
#
# skopeo payload:
# {
#   "schemaVersion": 2,
#   "mediaType": "application/vnd.oci.image.index.v1+json",
#   "manifests": [
#     {
#       "mediaType": "application/vnd.oci.image.manifest.v1+json",
#       "digest": "sha256:b4420a5954d33e55773d9d2024a605cb214217b5e5373fe735c771333c29b745",
#       "size": 14685,
#       "platform": {
#         "architecture": "amd64",
#         "os": "linux"
#       }
#     },
#     {
#       "mediaType": "application/vnd.oci.image.manifest.v1+json",
#       "digest": "sha256:e607922807982c135fefecb4fd2319fcedf24d963fd6a29fa3a942c0e1e58705",
#       "size": 14680,
#       "platform": {
#         "architecture": "arm64",
#         "os": "linux"
#       }
#     }
#   ]
# }
