FROM quay.io/fedora/fedora-coreos:stable

RUN cd /etc/yum.repos.d/ && \
    # Add Tailscale
    curl -LO https://pkgs.tailscale.com/stable/fedora/tailscale.repo && \
    rpm-ostree install tailscale && \
    systemctl enable tailscaled && \
    # Add cloudflared (Cloudflare Tunnel client)
    curl -LO https://pkg.cloudflare.com/cloudflared-ascii.repo && \
    rpm-ostree install cloudflared && \
    # Commit the container
    ostree container commit
